// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class retourBouteille_suiv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(retourBouteille_suiv));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141753240_retourBouteille_suiv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
