// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class devis_TypeReglement_correct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(devis_TypeReglement_correct));
        
        string IMigrationMetadata.Id
        {
            get { return "201703061201321_devis_TypeReglement_correct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
