// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class categorie_famille_article_bosh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categorie_famille_article_bosh));
        
        string IMigrationMetadata.Id
        {
            get { return "201702251844474_categorie_famille_article_bosh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
