// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bonavoircItem_numBL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bonavoircItem_numBL));
        
        string IMigrationMetadata.Id
        {
            get { return "201703121127239_bonavoircItem_numBL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
