// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rdb_rdbitem_client : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rdb_rdbitem_client));
        
        string IMigrationMetadata.Id
        {
            get { return "201703021736584_rdb_rdbitem_client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
