// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bonlivraison_typeReglement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bonlivraison_typeReglement));
        
        string IMigrationMetadata.Id
        {
            get { return "201703042119298_bonlivraison_typeReglement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
