// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class devis_suiv_typeReg_validationOffre_etc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(devis_suiv_typeReg_validationOffre_etc));
        
        string IMigrationMetadata.Id
        {
            get { return "201703051631376_devis_suiv_typeReg_validationOffre_etc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
