// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paiementF_factureF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paiementF_factureF));
        
        string IMigrationMetadata.Id
        {
            get { return "201810210743042_paiementF_factureF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
