// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class PaiementFacture_BonAvoirC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PaiementFacture_BonAvoirC));
        
        string IMigrationMetadata.Id
        {
            get { return "202006161905099_PaiementFacture_BonAvoirC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
