// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Site_BAItem_BACItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Site_BAItem_BACItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202007111209360_Site_BAItem_BACItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
