// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FakeFacturF_Ref_optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FakeFacturF_Ref_optional));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071133214_FakeFacturF_Ref_optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
