// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class WillCascadeOnDelete_TypeDepense_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WillCascadeOnDelete_TypeDepense_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "202006291744040_WillCascadeOnDelete_TypeDepense_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
