// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BonReception_Optional_BonAvoir : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BonReception_Optional_BonAvoir));
        
        string IMigrationMetadata.Id
        {
            get { return "202006181133054_BonReception_Optional_BonAvoir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
