// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sold_test_rollback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sold_test_rollback));
        
        string IMigrationMetadata.Id
        {
            get { return "202004181029313_sold_test_rollback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
