// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FakeFactur_TypePaiemet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FakeFactur_TypePaiemet));
        
        string IMigrationMetadata.Id
        {
            get { return "202005190158227_FakeFactur_TypePaiemet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
