// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Facture_DateEcheance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Facture_DateEcheance));
        
        string IMigrationMetadata.Id
        {
            get { return "202007071611204_Facture_DateEcheance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
