// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Client_IsClientDivers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Client_IsClientDivers));
        
        string IMigrationMetadata.Id
        {
            get { return "202007061850438_Client_IsClientDivers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
