// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BonLivraison_IdUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BonLivraison_IdUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202007042048245_BonLivraison_IdUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
