// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BL_TypePaiement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BL_TypePaiement));
        
        string IMigrationMetadata.Id
        {
            get { return "202005141334175_BL_TypePaiement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
