// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BIG_UPDATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BIG_UPDATE));
        
        string IMigrationMetadata.Id
        {
            get { return "202201221138260_BIG_UPDATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
